export const issuesTypes = {
  RETRIEVE_ISSUES_REQUEST: '[issues]RETRIEVE_ISSUES_REQUEST',
  RETRIEVE_ISSUES_SUCCESS: '[issues]RETRIEVE_ISSUES_SUCCESS',
  RETRIEVE_ISSUES_FAILURE: '[issues]RETRIEVE_ISSUES_FAILURE'
}
