export const issuesTypes = {
  RETRIEVE_ISSUES_REQUEST: '[issues]RETRIEVE_ISSUES_REQUEST',
  RETRIEVE_ISSUES_REQUEST_WITH_FILTER: '[issues]RETRIEVE_ISSUES_REQUEST_WITH_FILTER',
  RETRIEVE_ISSUES_SUCCESS: '[issues]LOGIN_SUCCESS',
  RETRIEVE_ISSUES_FAILURE: '[issues]LOGIN_FAILURE'
}
